export const province:string[] = [
  '河北省',
  '山西省',
  '内蒙古自治区',
  '辽宁省',
  '吉林省',
  '黑龙江省',
  '江苏省',
  '浙江省',
  '安徽省',
  '福建省',
  '江西省',
  '山东省',
  '河南省',
  '湖北省',
  '湖南省',
  '广东省',
  '广西壮族自治区',
  '海南省',
  '四川省',
  '贵州省',
  '云南省',
  '西藏自治区',
  '陕西省',
  '甘肃省',
  '青海省',
  '宁夏回族自治区',
  '新疆维吾尔自治区'
];

export const urban = [
  ['石家庄市', '唐山市', '秦皇岛市', '邯郸市', '邢台市', '保定市', '张家口市', '承德市', '沧州市', '廊坊市', '衡水市'],
  ['太原市', '大同市', '阳泉市', '长治市', '晋城市', '朔州市', '晋中市', '运城市', '忻州市', '临汾市', '吕梁市'],
  ['呼和浩特市', '包头市', '乌海市', '赤峰市', '通辽市', '鄂尔多斯市', '呼伦贝尔市', '巴彦淖尔市', '乌兰察布市'],
  ['沈阳市', '大连市', '鞍山市', '抚顺市', '本溪市', '丹东市', '锦州市', '营口市', '阜新市', '辽阳市', '盘锦市', '铁岭市', '朝阳市', '葫芦岛市'],
  ['长春市', '吉林市', '四平市', '辽源市', '通化市', '白山市', '松原市', '白城市'],
  ['哈尔滨市', '齐齐哈尔市', '鸡西市', '鹤岗市', '双鸭山市', '大庆市', '伊春市', '佳木斯市', '七台河市', '牡丹江市', '黑河市', '绥化市'],
  ['南京市', '无锡市', '徐州市', '常州市', '苏州市', '南通市', '连云港市', '淮安市', '盐城市', '扬州市', '镇江市', '泰州市', '宿迁市'],
  ['杭州市', '宁波市', '温州市', '嘉兴市', '湖州市', '绍兴市', '金华市', '衢州市', '舟山市', '台州市', '丽水市'],
  ['合肥市', '芜湖市', '蚌埠市', '淮南市', '马鞍山市', '淮北市', '铜陵市', '安庆市', '黄山市', '阜阳市', '宿州市', '滁州市', '六安市', '宣城市', '池州市', '亳州市'],
  ['福州市', '厦门市', '莆田市', '三明市', '泉州市', '漳州市', '南平市', '龙岩市', '宁德市'],
  ['南昌市', '景德镇市', '萍乡市', '九江市', '抚州市', '鹰潭市', '赣州市', '吉安市', '宜春市', '新余市', '上饶市'],
  ['济南市', '青岛市', '淄博市', '枣庄市', '东营市', '烟台市', '潍坊市', '济宁市', '泰安市', '威海市', '日照市', '临沂市', '德州市', '聊城市', '滨州市', '菏泽市'],
  ['郑州市', '开封市', '洛阳市', '平顶山市', '安阳市', '鹤壁市', '新乡市', '焦作市', '濮阳市', '许昌市', '漯河市', '三门峡市', '南阳市', '商丘市', '信阳市', '周口市', '驻马店市'],
  ['武汉市', '黄石市', '十堰市', '宜昌市', '襄阳市', '鄂州市', '荆门市', '孝感市', '荆州市', '黄冈市', '咸宁市', '随州市'],
  ['长沙市', '株洲市', '湘潭市', '衡阳市', '邵阳市', '岳阳市', '常德市', '张家界市', '益阳市', '郴州市', '永州市', '怀化市', '娄底市'],
  ['广州市', '韶关市', '深圳市', '珠海市', '汕头市', '佛山市', '江门市', '湛江市', '茂名市', '肇庆市', '惠州市', '梅州市', '汕尾市', '河源市', '阳江市', '清远市', '东莞市', '中山市', '潮州市', '揭阳市', '云浮市'],
  ['南宁市', '柳州市', '桂林市', '梧州市', '北海市', '防城港市', '钦州市', '贵港市', '玉林市', '百色市', '贺州市', '河池市', '来宾市', '崇左市'],
  ['海口市', '三亚市', '三沙市', '儋州市'],
  ['成都市', '自贡市', '攀枝花市', '泸州市', '德阳市', '绵阳市', '广元市', '遂宁市', '内江市', '乐山市', '南充市', '眉山市', '宜宾市', '广安市', '达州市', '雅安市', '巴中市', '资阳市'],
  ['贵阳市', '六盘水市', '遵义市', '安顺市', '毕节市', '铜仁市'],
  ['昆明市', '曲靖市', '玉溪市', '保山市', '昭通市', '丽江市', '普洱市', '临沧市'],
  ['拉萨市', '日喀则市', '昌都市', '林芝市', '山南市', '那曲市'],
  ['西安市', '铜川市', '宝鸡市', '咸阳市', '渭南市', '延安市', '汉中市', '榆林市', '安康市', '商洛市'],
  ['兰州市', '嘉峪关市', '金昌市', '白银市', '天水市', '武威市', '张掖市', '平凉市', '酒泉市', '庆阳市', '定西市', '陇南市'],
  ['西宁市', '海东市'],
  ['银川市', '石嘴山市', '吴忠市', '固原市', '中卫市'],
  ['乌鲁木齐市', '克拉玛依市', '吐鲁番市', '哈密市']
]

export const labels = () => {
  return [
    [
      { value: '电音迷', selected: false },
      { value: '常年出没音乐节', selected: false },
      { value: '偏爱后摇house爱好者', selected: false },
      { value: '摇滚乐迷', selected: false },
      { value: '热爱纯音乐', selected: false },
      { value: '沉迷国风音乐', selected: false },
      { value: '什么类型都听听', selected: false },
      { value: 'K-POP爱好者', selected: false },
      { value: '民谣深度中毒', selected: false },
      { value: '古典乐爱好者', selected: false },
      { value: '小语种音乐迷', selected: false },
      { value: '最爱粤语歌', selected: false },
      { value: '古风戏腔迷', selected: false },
      { value: '爵士老灵魂', selected: false },
      { value: '专注说唱三十年', selected: false },
      { value: '欧美音乐发烧友', selected: false },
      { value: '颜人中歌迷', selected: false },
      { value: '独立音乐挖掘机', selected: false },
      { value: '爱听老歌', selected: false },
      { value: '沉醉乡村音乐', selected: false },
      { value: '姜云升的粉丝', selected: false },
      { value: 'VOCALOID厨', selected: false },
      { value: '时代少年团团友', selected: false },
      { value: '毛不易的暴发户', selected: false }
    ],
    [
      { value: 'ACG爱好者', selected: false },
      { value: '游戏宅', selected: false },
      { value: '纸片人赛高', selected: false },
      { value: '三坑少女', selected: false },
      { value: '汉服同袍', selected: false },
      { value: '电波系', selected: false },
      { value: '黑胶收藏者', selected: false },
      { value: '业余小提琴手', selected: false },
      { value: '中二病少年', selected: false },
      { value: '实体唱片控', selected: false },
      { value: '设圈同好', selected: false },
      { value: '野生画师', selected: false },
      { value: '爆裂鼓手', selected: false },
      { value: '指弹狂魔', selected: false },
      { value: '吉他新手', selected: false },
      { value: '观影爱好者', selected: false },
      { value: '美剧十级学者', selected: false },
      { value: '漫威粉', selected: false },
      { value: '综艺小百科', selected: false },
      { value: '复古老灵魂', selected: false },
      { value: '蒸汽波爱好者', selected: false },
      { value: '魂穿80年代', selected: false },
      { value: '阴阳师中毒', selected: false },
      { value: '峡谷小学生', selected: false },
      { value: '小说阅读十级', selected: false },
      { value: '爆肝FGO', selected: false },
      { value: '贝斯手', selected: false },
      { value: '快乐追星人', selected: false },
      { value: '音游人', selected: false },
      { value: '刀客塔', selected: false },
  
    ],
    [
      { value: '尊贵的LV10用户', selected: false },
      { value: '野生音乐人', selected: false },
      { value: '音乐制作人', selected: false },
      { value: '小众歌单收集控', selected: false },
      { value: '野生主播', selected: false },
      { value: "I'm a DJ", selected: false },
      { value: '卧室K歌爱好者', selected: false },
      { value: '点赞狂魔', selected: false },
      { value: '歌词翻译者', selected: false },
      { value: '评论区乐评人', selected: false },
      { value: '热评狂魔', selected: false },
      { value: '动态话痨', selected: false },
      { value: '资深社畜', selected: false },
      { value: '五音不全', selected: false },
      { value: '海外时差党', selected: false },
      { value: '人形自走etc', selected: false },
      { value: '文科生', selected: false },
      { value: '理科生', selected: false },
      { value: '学生党', selected: false },
      { value: '野生声优', selected: false },
      { value: '蹦迪艺术家', selected: false },
      { value: '文艺青年', selected: false },
      { value: '颜控的自我修养', selected: false },
      { value: '酒后行为艺术家', selected: false },
      { value: '爱好整活', selected: false },
      { value: '加班狂魔', selected: false },
      { value: '高级职业键盘侠', selected: false },
      { value: '社恐患者', selected: false },
      { value: '沙雕小盆友', selected: false },
      { value: '欢迎扩列', selected: false },
      { value: '逃避可耻但有用', selected: false },
      { value: '家有猫主子', selected: false },
      { value: '校草就是我', selected: false },
    ]
  ]
}
